#!/bin/bash

echo "Run project containers"

param1=$1
param2=$2

run_container() {
    local dir=$1
    local name=$2
    local action=${param2:-up}

    cd "./$dir" || exit 1
    if [ "$action" = "stop" ]; then
        docker compose down
        echo "$name Stopped"
    else
        docker compose up -d
        echo "$name Running"
    fi
    cd - > /dev/null
}

if [ "$param1" = "--mysql57" ]; then
    run_container mysql57 "MySQL 5.7"
elif [ "$param1" = "--mysql84" ] ; then
    run_container mysql8 "MySQL 8"
elif [ "$param1" = "--postgres" ]; then
    run_container postgresql "PostgreSQL"
elif [ "$param1" = "--redis" ]; then
    run_container redis "Redis"
elif [ "$param1" = "--nginx" ]; then
    run_container nginx "Nginx"
elif [ "$param1" = "--jenkins" ]; then
    run_container jenkins "Jenkins"
elif [ "$param1" = "--kafka" ]; then
    run_container kafka "Kafka"
elif [ "$param1" = "--mailhog" ]; then
    run_container mailhog "Mailhog"
elif [ "$param1" = "--rabbitmq" ]; then
    run_container rabbitmq "RabbitMQ"
elif [ "$param1" = "--php" ]; then
    run_container php "PHP"
elif [ "$param1" = "--oracle" ]; then
    run_container oracle-xe "Oracle XE"
elif [ "$param1" = "--nodejs" ]; then
    run_container nodejs "NodeJS"
elif [ "$param1" = "--all" ]; then
    ./containers --mysql57
    ./containers --mysql84
    ./containers --postgres
    ./containers --redis
    ./containers --nginx
    ./containers --jenkins
    ./containers --kafka
    ./containers --mailhog
    ./containers --rabbitmq
    ./containers --php
    ./containers --oracle
    ./containers --nodejs
else
    echo "Usage: ./containers [--mysql57] [--mysql84] [--postgres] [--redis] [--nginx] [--jenkins]"
    echo "                    [--kafka] [--mailhog] [--rabbitmq] [--php] [--oracle] [--nodejs]"
    echo "                    [--all]"
    echo "Append 'stop' to stop a container. Example: ./containers --redis stop"
fi
