services:
  db57:
    container_name: mysql57-containers
    image: mysql57-containers
    platform: linux/amd64
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "3357:3306"
    volumes:
      - mysql57_data:/var/lib/mysql
      - ./configs/db57.cnf:/etc/mysql/conf.d/db57.cnf
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=secret
    restart: unless-stopped

volumes:
  mysql57_data:
    driver: local
