version: '3'

services:
  db57:
    container_name: mysql57-containers
    image: mysql57-containers
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 3357:3306
    volumes:
      - ./data:/var/lib/mysql
      - ./configs/db57.cnf:/etc/mysql/conf.d/db57.cnf
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=secret
    working_dir: /var/lib/mysql
