version: '3.9'

services:
  app:
    container_name: php82-container
    image: php82-container
    build: 
      context: .
      dockerfile: ./Dockerfile
    working_dir: /app
    ports:
      - 9000:9000
    volumes:
      - ./www:/app
  webserver:
    container_name: php82-nginx-container
    image: nginx:latest
    volumes:
      - ./www:/var/www
      - ./configs/website.conf:/etc/nginx/conf.d/default.conf
      - ./logs:/var/log/nginx
    ports:
      - 8000:80
    working_dir: /var/www