services:
  redis:
    container_name: redis-containers
    image: redis:latest
    restart: always
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD}
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - data_redis:/data

volumes:
  data_redis:
    driver: local
