version: '3.9'

services:
  redis:
    container_name: redis-containers
    image: redis:latest
    command: redis-server --requirepass secret
    ports:
      - 6379:6379
    volumes:
      - data_redis:/data

volumes:
  data_redis:
    driver: local
